### ISSUE TITLE
Swagger UI "Not Found" with Pedestal 0.5.2

### ISSUE THREAD

**Issue by lerouxrgd** [oliyh/pedestal-api#17] opened 2017-01-18 07:17 UTC
Hi,
It looks like after updating to Pedestal 0.5.2
```clj
["some/custom/route/*resource" {:get api/swagger-ui}]
```
doesn't compile to correct route and I get "Not Found" page instead of usual Swagger UI.

**Comment by oliyh** [comment] 2017-01-18 08:07
Hi @lerouxrgd,

I just found the same issue myself. Thanks for pointing it out, I'll get it fixed soon.

**Comment by oliyh** [comment] 2017-01-18 20:33
Hi @lerouxrgd 

I have raised a PR against route-swagger with the details of the root cause:
https://github.com/frankiesardo/route-swagger/pull/32
Once this is merged and released I'll create a new release of pedestal-api.

In the meantime you might have some luck with explicitly using an older version of ring-core.

**Closed as completed** 2017-01-20 18:43 UTC

**Comment by oliyh** [comment] 2017-01-20 18:50
Fixed in `0.3.1`
